# Generated by Django 3.1.4 on 2021-02-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210213_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/articles', verbose_name='картинка, которая будет показываться в списке статей'),
        ),
    ]
