# Generated by Django 3.1.4 on 2021-05-31 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'картинки галлереи', 'verbose_name_plural': 'картинки галлереи'},
        ),
    ]
