# Generated by Django 3.1.4 on 2021-02-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.CharField(max_length=50, verbose_name='имейл, который будет показываться на каждой странице сайта')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='номер телефона, который будет показываться на каждой странице сайта')),
            ],
        ),
        migrations.AlterModelOptions(
            name='kidsgroup',
            options={'verbose_name': 'группа детей', 'verbose_name_plural': 'группы детей'},
        ),
    ]
