# Generated by Django 3.1.4 on 2021-02-10 20:08

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210210_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='название страницы')),
                ('content', models.TextField(verbose_name='текст страницы')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='slug')),
            ],
        ),
        migrations.AlterModelOptions(
            name='generalinfo',
            options={'verbose_name': 'общая информация', 'verbose_name_plural': 'общая информация'},
        ),
    ]
