# Generated by Django 3.1.4 on 2021-02-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210210_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopages',
            name='slug',
        ),
        migrations.AlterField(
            model_name='infopages',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='название страницы'),
        ),
    ]
