# Generated by Django 3.1.4 on 2021-03-07 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210211_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infopages',
            options={'verbose_name': 'дополнительная страница', 'verbose_name_plural': 'дополнительные страницы'},
        ),
    ]
